//
// RulesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire
import PromiseKit



public class RulesAPI: APIBase {
    /**
     
     Create Rule
     
     - parameter ruleInfo: (body) Rule object that needs to be added 
     - parameter userId: (query) User ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createRule(ruleInfo ruleInfo: RuleCreationInfo, userId: String, completion: ((data: RuleEnvelope?, error: ErrorType?) -> Void)) {
        createRuleWithRequestBuilder(ruleInfo: ruleInfo, userId: userId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }

    /**
     
     Create Rule
     
     - parameter ruleInfo: (body) Rule object that needs to be added 
     - parameter userId: (query) User ID 
     - returns: Promise<RuleEnvelope>
     */
    public class func createRule(ruleInfo ruleInfo: RuleCreationInfo, userId: String) -> Promise<RuleEnvelope> {
        let deferred = Promise<RuleEnvelope>.pendingPromise()
        createRule(ruleInfo: ruleInfo, userId: userId) { data, error in
            if let error = error {
                deferred.reject(error)
            } else {
                deferred.fulfill(data!)
            }
        }
        return deferred.promise
    }

    /**
     
     Create Rule
     
     - POST /rules
     - Create a new Rule
     - OAuth:
       - type: oauth2
       - name: artikcloud_oauth
     - examples: [{contentType=application/json, example={
  "data" : {
    "languageVersion" : 123,
    "description" : "aeiou",
    "index" : 123,
    "rule" : {
      "key" : ""
    },
    "error" : {
      "messageKey" : "aeiou",
      "fieldPath" : {
        "path" : [ {
          "text" : "aeiou"
        } ]
      },
      "messageArgs" : [ "" ],
      "errorCode" : 123
    },
    "createdOn" : 123456789,
    "enabled" : true,
    "uid" : "aeiou",
    "modifiedOn" : 123456789,
    "name" : "aeiou",
    "warning" : {
      "code" : "aeiou",
      "message" : "aeiou"
    },
    "invalidatedOn" : 123456789,
    "id" : "aeiou",
    "aid" : "aeiou"
  }
}}]
     
     - parameter ruleInfo: (body) Rule object that needs to be added 
     - parameter userId: (query) User ID 

     - returns: RequestBuilder<RuleEnvelope> 
     */
    public class func createRuleWithRequestBuilder(ruleInfo ruleInfo: RuleCreationInfo, userId: String) -> RequestBuilder<RuleEnvelope> {
        let path = "/rules"
        let URLString = ArtikCloudAPI.basePath + path
        
        let parameters = ruleInfo.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<RuleEnvelope>.Type = ArtikCloudAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: false)
    }

    /**
     
     Delete Rule
     
     - parameter ruleId: (path) Rule ID. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteRule(ruleId ruleId: String, completion: ((data: RuleEnvelope?, error: ErrorType?) -> Void)) {
        deleteRuleWithRequestBuilder(ruleId: ruleId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }

    /**
     
     Delete Rule
     
     - parameter ruleId: (path) Rule ID. 
     - returns: Promise<RuleEnvelope>
     */
    public class func deleteRule(ruleId ruleId: String) -> Promise<RuleEnvelope> {
        let deferred = Promise<RuleEnvelope>.pendingPromise()
        deleteRule(ruleId: ruleId) { data, error in
            if let error = error {
                deferred.reject(error)
            } else {
                deferred.fulfill(data!)
            }
        }
        return deferred.promise
    }

    /**
     
     Delete Rule
     
     - DELETE /rules/{ruleId}
     - Delete a Rule
     - OAuth:
       - type: oauth2
       - name: artikcloud_oauth
     - examples: [{contentType=application/json, example={
  "data" : {
    "languageVersion" : 123,
    "description" : "aeiou",
    "index" : 123,
    "rule" : {
      "key" : ""
    },
    "error" : {
      "messageKey" : "aeiou",
      "fieldPath" : {
        "path" : [ {
          "text" : "aeiou"
        } ]
      },
      "messageArgs" : [ "" ],
      "errorCode" : 123
    },
    "createdOn" : 123456789,
    "enabled" : true,
    "uid" : "aeiou",
    "modifiedOn" : 123456789,
    "name" : "aeiou",
    "warning" : {
      "code" : "aeiou",
      "message" : "aeiou"
    },
    "invalidatedOn" : 123456789,
    "id" : "aeiou",
    "aid" : "aeiou"
  }
}}]
     
     - parameter ruleId: (path) Rule ID. 

     - returns: RequestBuilder<RuleEnvelope> 
     */
    public class func deleteRuleWithRequestBuilder(ruleId ruleId: String) -> RequestBuilder<RuleEnvelope> {
        var path = "/rules/{ruleId}"
        path = path.stringByReplacingOccurrencesOfString("{ruleId}", withString: "\(ruleId)", options: .LiteralSearch, range: nil)
        let URLString = ArtikCloudAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<RuleEnvelope>.Type = ArtikCloudAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Get Rule
     
     - parameter ruleId: (path) Rule ID. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getRule(ruleId ruleId: String, completion: ((data: RuleEnvelope?, error: ErrorType?) -> Void)) {
        getRuleWithRequestBuilder(ruleId: ruleId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }

    /**
     
     Get Rule
     
     - parameter ruleId: (path) Rule ID. 
     - returns: Promise<RuleEnvelope>
     */
    public class func getRule(ruleId ruleId: String) -> Promise<RuleEnvelope> {
        let deferred = Promise<RuleEnvelope>.pendingPromise()
        getRule(ruleId: ruleId) { data, error in
            if let error = error {
                deferred.reject(error)
            } else {
                deferred.fulfill(data!)
            }
        }
        return deferred.promise
    }

    /**
     
     Get Rule
     
     - GET /rules/{ruleId}
     - Get a rule using the Rule ID
     - OAuth:
       - type: oauth2
       - name: artikcloud_oauth
     - examples: [{contentType=application/json, example={
  "data" : {
    "languageVersion" : 123,
    "description" : "aeiou",
    "index" : 123,
    "rule" : {
      "key" : ""
    },
    "error" : {
      "messageKey" : "aeiou",
      "fieldPath" : {
        "path" : [ {
          "text" : "aeiou"
        } ]
      },
      "messageArgs" : [ "" ],
      "errorCode" : 123
    },
    "createdOn" : 123456789,
    "enabled" : true,
    "uid" : "aeiou",
    "modifiedOn" : 123456789,
    "name" : "aeiou",
    "warning" : {
      "code" : "aeiou",
      "message" : "aeiou"
    },
    "invalidatedOn" : 123456789,
    "id" : "aeiou",
    "aid" : "aeiou"
  }
}}]
     
     - parameter ruleId: (path) Rule ID. 

     - returns: RequestBuilder<RuleEnvelope> 
     */
    public class func getRuleWithRequestBuilder(ruleId ruleId: String) -> RequestBuilder<RuleEnvelope> {
        var path = "/rules/{ruleId}"
        path = path.stringByReplacingOccurrencesOfString("{ruleId}", withString: "\(ruleId)", options: .LiteralSearch, range: nil)
        let URLString = ArtikCloudAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<RuleEnvelope>.Type = ArtikCloudAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Update Rule
     
     - parameter ruleId: (path) Rule ID. 
     - parameter ruleInfo: (body) Rule object that needs to be updated 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateRule(ruleId ruleId: String, ruleInfo: RuleUpdateInfo, completion: ((data: RuleEnvelope?, error: ErrorType?) -> Void)) {
        updateRuleWithRequestBuilder(ruleId: ruleId, ruleInfo: ruleInfo).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }

    /**
     
     Update Rule
     
     - parameter ruleId: (path) Rule ID. 
     - parameter ruleInfo: (body) Rule object that needs to be updated 
     - returns: Promise<RuleEnvelope>
     */
    public class func updateRule(ruleId ruleId: String, ruleInfo: RuleUpdateInfo) -> Promise<RuleEnvelope> {
        let deferred = Promise<RuleEnvelope>.pendingPromise()
        updateRule(ruleId: ruleId, ruleInfo: ruleInfo) { data, error in
            if let error = error {
                deferred.reject(error)
            } else {
                deferred.fulfill(data!)
            }
        }
        return deferred.promise
    }

    /**
     
     Update Rule
     
     - PUT /rules/{ruleId}
     - Update an existing Rule
     - OAuth:
       - type: oauth2
       - name: artikcloud_oauth
     - examples: [{contentType=application/json, example={
  "data" : {
    "languageVersion" : 123,
    "description" : "aeiou",
    "index" : 123,
    "rule" : {
      "key" : ""
    },
    "error" : {
      "messageKey" : "aeiou",
      "fieldPath" : {
        "path" : [ {
          "text" : "aeiou"
        } ]
      },
      "messageArgs" : [ "" ],
      "errorCode" : 123
    },
    "createdOn" : 123456789,
    "enabled" : true,
    "uid" : "aeiou",
    "modifiedOn" : 123456789,
    "name" : "aeiou",
    "warning" : {
      "code" : "aeiou",
      "message" : "aeiou"
    },
    "invalidatedOn" : 123456789,
    "id" : "aeiou",
    "aid" : "aeiou"
  }
}}]
     
     - parameter ruleId: (path) Rule ID. 
     - parameter ruleInfo: (body) Rule object that needs to be updated 

     - returns: RequestBuilder<RuleEnvelope> 
     */
    public class func updateRuleWithRequestBuilder(ruleId ruleId: String, ruleInfo: RuleUpdateInfo) -> RequestBuilder<RuleEnvelope> {
        var path = "/rules/{ruleId}"
        path = path.stringByReplacingOccurrencesOfString("{ruleId}", withString: "\(ruleId)", options: .LiteralSearch, range: nil)
        let URLString = ArtikCloudAPI.basePath + path
        
        let parameters = ruleInfo.encodeToJSON() as? [String:AnyObject]

        let requestBuilder: RequestBuilder<RuleEnvelope>.Type = ArtikCloudAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: true)
    }

}
