//
// Acknowledgement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Acknowledgement received by a WebSocket in response to a RegisterMessage, MessageIn or ActionIn. */
public class Acknowledgement: JSONEncodable {

    /** Message ID. */
    public var mid: String?
    /** Confirmation ID. */
    public var cid: String?
    /** Message. */
    public var message: String?
    /** Code */
    public var code: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["mid"] = self.mid
        nillableDictionary["cid"] = self.cid
        nillableDictionary["message"] = self.message
        nillableDictionary["code"] = self.code
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
