//
// ActionOut.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Action received in a WebSocket. */
public class ActionOut: JSONEncodable {
    /** Message ID. */
    public var mid: String?
    /** User ID. */
    public var uid: String?
    /** Source Device Type ID. */
    public var sdtid: String?
    /** Created Timestamp (past, present or future). Defaults to current time if not provided. */
    public var cts: Int64?
    /** Manifest Version. */
    public var mv: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["mid"] = self.mid
        nillableDictionary["uid"] = self.uid
        nillableDictionary["sdtid"] = self.sdtid
        nillableDictionary["cts"] = self.cts?.encodeToJSON()
        nillableDictionary["mv"] = self.mv?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
