//
// DeviceToken.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Device Token */
public class DeviceToken: JSONEncodable {

    public var accessToken: String?
    public var uid: String?
    public var did: String?
    public var cid: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["accessToken"] = self.accessToken
        nillableDictionary["uid"] = self.uid
        nillableDictionary["did"] = self.did
        nillableDictionary["cid"] = self.cid
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
