//
// DeviceRegConfirmUserRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class DeviceRegConfirmUserRequest: JSONEncodable {
    /** Device ID. Optional if deviceName is present */
    public var deviceId: String?
    /** Device Name. Optional if deviceId is present */
    public var deviceName: String?
    /** Pin obtained in the registrations call. */
    public var pin: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["deviceId"] = self.deviceId
        nillableDictionary["deviceName"] = self.deviceName
        nillableDictionary["pin"] = self.pin
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
