//
// DevicesEnvelope.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Devices Envelope */
public class DevicesEnvelope: JSONEncodable {

    public var total: Int?
    public var count: Int?
    public var offset: Int?
    public var data: DeviceArray?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["total"] = self.total
        nillableDictionary["count"] = self.count
        nillableDictionary["offset"] = self.offset
        nillableDictionary["data"] = self.data?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
