//
// DeviceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Device Type Information */
public class DeviceType: JSONEncodable {
    /** Device Type ID. */
    public var id: String?
    /** Unique Name. */
    public var uniqueName: String?
    /** Latest Manifest version. */
    public var latestVersion: Int32?
    public var lastUpdated: Int64?
    /** Name. */
    public var name: String?
    /** Description. */
    public var description: String?
    /** User ID. */
    public var uid: String?
    /** Organization ID. */
    public var oid: String?
    /** Uses Cloud Connectors SDK */
    public var hasCloudConnector: Bool?
    /** Approval status. */
    public var approved: Bool?
    /** Published status. */
    public var published: Bool?
    /** Protected status. */
    public var protected: Bool?
    /** In Store. */
    public var inStore: Bool?
    /** Does the current user own a device of this device type */
    public var ownedByCurrentUser: Bool?
    /** Tags */
    public var tags: [Tag]?
    /** Require Secure Device Registration (SDR) Protocol. */
    public var rsp: Bool?
    /** Issuer Distinguished Name (Used in SDR) */
    public var issuerDn: String?
    /** Vendor ID. (Used in SDR) */
    public var vid: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["uniqueName"] = self.uniqueName
        nillableDictionary["latestVersion"] = self.latestVersion?.encodeToJSON()
        nillableDictionary["lastUpdated"] = self.lastUpdated?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["description"] = self.description
        nillableDictionary["uid"] = self.uid
        nillableDictionary["oid"] = self.oid
        nillableDictionary["hasCloudConnector"] = self.hasCloudConnector
        nillableDictionary["approved"] = self.approved
        nillableDictionary["published"] = self.published
        nillableDictionary["protected"] = self.protected
        nillableDictionary["inStore"] = self.inStore
        nillableDictionary["ownedByCurrentUser"] = self.ownedByCurrentUser
        nillableDictionary["tags"] = self.tags?.encodeToJSON()
        nillableDictionary["rsp"] = self.rsp
        nillableDictionary["issuerDn"] = self.issuerDn
        nillableDictionary["vid"] = self.vid
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
