//
// ExportStatusResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Export Status Response. */
public class ExportStatusResponse: JSONEncodable {

    public var expirationDate: Int?
    public var exportId: String?
    public var md5: String?
    /** Export status */
    public var status: String?
    public var ttl: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["expirationDate"] = self.expirationDate
        nillableDictionary["exportId"] = self.exportId
        nillableDictionary["md5"] = self.md5
        nillableDictionary["status"] = self.status
        nillableDictionary["ttl"] = self.ttl
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
