//
// ExportNormalizedMessagesResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Export Normalized Messages Response. */
public class ExportNormalizedMessagesResponse: JSONEncodable {

    public var csvHeaders: Bool?
    public var endDate: Int?
    public var exportId: String?
    public var format: String?
    public var order: String?
    public var sdid: String?
    public var sdids: String?
    public var startDate: Int?
    public var stdids: String?
    public var trialId: String?
    public var uid: String?
    public var uids: String?
    public var url: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["csvHeaders"] = self.csvHeaders
        nillableDictionary["endDate"] = self.endDate
        nillableDictionary["exportId"] = self.exportId
        nillableDictionary["format"] = self.format
        nillableDictionary["order"] = self.order
        nillableDictionary["sdid"] = self.sdid
        nillableDictionary["sdids"] = self.sdids
        nillableDictionary["startDate"] = self.startDate
        nillableDictionary["stdids"] = self.stdids
        nillableDictionary["trialId"] = self.trialId
        nillableDictionary["uid"] = self.uid
        nillableDictionary["uids"] = self.uids
        nillableDictionary["url"] = self.url
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
