//
// FieldsActions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Fields and Actions */
public class FieldsActions: JSONEncodable {
    /** Message Fields */
    public var fields: [String:AnyObject]?
    /** Actions */
    public var actions: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["fields"] = self.fields?.encodeToJSON()
        nillableDictionary["actions"] = self.actions?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
