//
// NormalizedMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Normalized Message */
public class NormalizedMessage: JSONEncodable {

    public var cts: Int?
    public var ts: Int?
    public var mid: String?
    public var sdid: String?
    public var sdtid: String?
    public var uid: String?
    public var mv: Int?
    public var data: [String:AnyObject]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cts"] = self.cts
        nillableDictionary["ts"] = self.ts
        nillableDictionary["mid"] = self.mid
        nillableDictionary["sdid"] = self.sdid
        nillableDictionary["sdtid"] = self.sdtid
        nillableDictionary["uid"] = self.uid
        nillableDictionary["mv"] = self.mv
        nillableDictionary["data"] = self.data?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
