//
// NormalizedActionsEnvelope.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Normalized Actions Envelope */
public class NormalizedActionsEnvelope: JSONEncodable {
    public var ddids: String?
    public var ddid: String?
    public var uid: String?
    public var startDate: Int64?
    public var endDate: Int64?
    public var order: String?
    public var next: String?
    public var count: Int64?
    public var size: Int64?
    public var data: [NormalizedAction]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ddids"] = self.ddids
        nillableDictionary["ddid"] = self.ddid
        nillableDictionary["uid"] = self.uid
        nillableDictionary["startDate"] = self.startDate?.encodeToJSON()
        nillableDictionary["endDate"] = self.endDate?.encodeToJSON()
        nillableDictionary["order"] = self.order
        nillableDictionary["next"] = self.next
        nillableDictionary["count"] = self.count?.encodeToJSON()
        nillableDictionary["size"] = self.size?.encodeToJSON()
        nillableDictionary["data"] = self.data?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
