//
// NormalizedAction.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Normalized Action */
public class NormalizedAction: JSONEncodable {
    public var cts: Int64?
    public var ts: Int64?
    public var mid: String?
    public var sdid: String?
    public var ddid: String?
    public var ddtid: String?
    public var uid: String?
    public var mv: Int32?
    public var data: ActionArray?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cts"] = self.cts?.encodeToJSON()
        nillableDictionary["ts"] = self.ts?.encodeToJSON()
        nillableDictionary["mid"] = self.mid
        nillableDictionary["sdid"] = self.sdid
        nillableDictionary["ddid"] = self.ddid
        nillableDictionary["ddtid"] = self.ddtid
        nillableDictionary["uid"] = self.uid
        nillableDictionary["mv"] = self.mv?.encodeToJSON()
        nillableDictionary["data"] = self.data?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
