//
// RefreshTokenResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class RefreshTokenResponse: JSONEncodable {

    public var accessToken: String?
    public var expiresIn: Int?
    public var refreshToken: String?
    public var tokenType: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["access_token"] = self.accessToken
        nillableDictionary["expires_in"] = self.expiresIn
        nillableDictionary["refresh_token"] = self.refreshToken
        nillableDictionary["token_type"] = self.tokenType
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
