//
// RefreshTokenResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */
public class RefreshTokenResponse: JSONEncodable {

    public var accessToken: String?
    public var expiresIn: Int?
    public var refreshToken: String?
    public var tokenType: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["accessToken"] = self.accessToken
        nillableDictionary["expiresIn"] = self.expiresIn
        nillableDictionary["refreshToken"] = self.refreshToken
        nillableDictionary["tokenType"] = self.tokenType
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
