//
// RegisterMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** WebSocket Registration Message */
public class RegisterMessage: JSONEncodable {
    /** Confirmation ID. */
    public var cid: String?
    /** Authorization header containing access token (Bearer &lt;access_token&gt;). */
    public var authorization: String?
    /** Source Device ID. */
    public var sdid: String?
    /** Timestamp (past, present or future). Defaults to current time if not provided. */
    public var ts: Int64?
    /** Type. */
    public var type: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cid"] = self.cid
        nillableDictionary["authorization"] = self.authorization
        nillableDictionary["sdid"] = self.sdid
        nillableDictionary["ts"] = self.ts?.encodeToJSON()
        nillableDictionary["type"] = self.type
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
