//
// RuleUpdateInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class to update an existing Rule. */
public class RuleUpdateInfo: JSONEncodable {

    /** Description */
    public var description: String?
    /** Is Enabled */
    public var enabled: Bool?
    /** Name */
    public var name: String?
    /** Rule */
    public var rule: [String:AnyObject]?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["description"] = self.description
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["name"] = self.name
        nillableDictionary["rule"] = self.rule?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
