//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** User Information */
public class User: JSONEncodable {
    public var id: String?
    public var name: String?
    public var email: String?
    public var fullName: String?
    public var saIdentity: String?
    public var createdOn: Int64?
    public var modifiedOn: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["email"] = self.email
        nillableDictionary["fullName"] = self.fullName
        nillableDictionary["saIdentity"] = self.saIdentity
        nillableDictionary["createdOn"] = self.createdOn?.encodeToJSON()
        nillableDictionary["modifiedOn"] = self.modifiedOn?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
