//
// WebSocketError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** WebSocket Error Information */
public class WebSocketError: JSONEncodable {

    /** Message. */
    public var message: String?
    /** Code */
    public var code: Int?
    /** Confirmation ID */
    public var cid: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["message"] = self.message
        nillableDictionary["code"] = self.code
        nillableDictionary["cid"] = self.cid
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
